---
- debug: msg="config changed"

- name: ensure fact file
  copy: contents=files/empty-fact-file.ini
        dest=/etc/ansible/facts.d/docker.fact
        force=no

- name: ensure swarm container
  docker:
    name: swarm
    image: swarm
    state: present

- name: add upstart job for socat
  copy: src=files/socat-upstart.conf dest=/etc/init/swarm-docker-port.conf
  notify: restart socat

- include: load-facts.yml

# if reloaded is reset, notify
- name: reload containers
  ini_file: "dest={{docker_facts}}
             section=state
             option=reload
             value=''
             backup=yes"
  notify:
    - join cluster
    - manage cluster
    - open management port
