---
- debug: msg="config changed"

- name: ensure swarm container
  docker:
    name: swarm
    image: swarm
    state: present

- name: add upstart job for socat
  copy: src=files/socat-upstart.conf dest=/etc/init/swarm-docker-port.conf
  notify: restart socat

- set_fact:
    join_command: "{{ansible_local.swarm.command.join|default('')}}"
    manage_command: "{{ansible_local.swarm.command.manage|default('')}}"
    reload: "{{ansible_local.swarm.state.reload|default('')}}"

# if reloaded is reset, notify
- name: reload containers
  ini_file: "dest=/etc/ansible/facts.d/swarm.fact
             section=state
             option=reload
             value=''
             backup=yes"
  notify:
    - join cluster
    - manage cluster
    - open management port
