---
- debug: msg="config changed"

- name: ensure swarm container
  docker:
    name: swarm
    image: swarm
    state: present

- set_fact:
    join_command: "{{ansible_local.run.command.join|default('')}}"
    manage_command: "{{ansible_local.run.command.manage|default('')}}"
    reload: "{{ansible_local.run.state.reload|default('')}}"

- name: launch join
  debug: msg="reload containers"
  notify:
    - join cluster
    - manage cluster
    - reloaded
  when: reload
