---
## Setup fact.d file for launching our docker containers

- name: set commands
  set_fact:
    join_command: "join --addr={{unit_private_address}}:2375 etcd://{{current_relation.hostname}}:{{current_relation.port}}/{{discovery_path}}"
    manage_command: "manage -H tcp://{{unit_private_address}}:2375 etcd://{{current_relation.hostname}}:{{current_relation.port}}/{{discovery_path}}"

- name: set join command
  ini_file: "dest=/etc/ansible/facts.d/swarm.fact
             section=command
             option=join
             value='{{join_command}}'
             backup=yes"
  notify:
    - join cluster

- name: set manage command
  ini_file: "dest=/etc/ansible/facts.d/swarm.fact
             section=command
             option=manage
             value='{{manage_command}}'
             backup=yes"
  notify:
    - manage cluster
    - open management port


- name: set reload
  ini_file: "dest=/etc/ansible/facts.d/swarm.fact
             section=state
             option=reload
             value=True
             backup=yes"