---
- debug: msg="etcd"

- name: join cluster
  docker: 
    command="join --addr={{unit_private_address}}:2375 etcd://{{current_relation.hostname}}:{{current_relation.port}}/juju-swarm"
    image=swarm
    state=reloaded
    detach=true
    publish_all_ports=True