---
- hosts: all
  vars:
    docker_facts: /etc/ansible/facts.d/docker.fact
    nodes_file: /etc/swarm-nodes.txt
  handlers:
    # # once we have tls/ssl
    # - name: open docker port
    #   command: open-port 2375
    # - name: close docker port
    #   command: close-port 2375

    - name: restart socat
      service: name=swarm-docker-port state=restarted

    - name: join cluster
      docker:
        command="{{join_command}}"
        image=swarm
        state=reloaded
        restart_policy=always
        detach=true
        name="swarm-node"

    - name: manage cluster
      docker:
        command="{{manage_command}}"
        image=swarm
        state=reloaded
        restart_policy=always
        detach=true
        ports=5001:2375
        name="swarm-manage"

    - name: open management port
      command: open-port 5001

    - name: close management port
      command: close-port 5001

  tasks:
    - include: config-changed.yml
      tags:
        - config-changed

    - include: upgrade-charm.yml
      tags:
        - upgrade-charm

    - include: docker-cluster.yml
      tags:
        - docker-cluster-relation-changed

    - include: register-changed.yml
      tags:
        - register-relation-changed

    - include: register-broken.yml
      tags:
        - register-relation-broken

    - include: etcd.yml
      tags:
        - etcd-relation-changed

    - include: consul.yml
      tags:
        - consul-relation-changed

    - include: state-server-cmd.yml
      tags:
        - etcd-relation-changed
        - consul-relation-changed