---
- hosts: all
  handlers:

    - name: reloaded
      ini_file: "dest=/etc/ansible/fact.d/run.fact
                 section=state
                 option=reload
                 value=''
                 backup=yes"

    - name: join cluster
      docker:
        command="{{join_command}}"
        image=swarm
        state=reloaded
        restart_policy=always
        detach=true
        publish_all_ports=True
        name="swarm-node"
        port={{unit_private_address}}:2375:2375
    - name: manage cluster
      docker:
        command="{{manage_command}}"
        image=swarm
        state=reloaded
        restart_policy=always
        detach=true
        port={{unit_private_address}}:2376:2376
        publish_all_ports=True
        name="swarm-manage"
  tasks:
    - debug: msg="wat"
      tags:
        - config-changed
        - upgrade-charm

    - include: config-changed.yml
      tags:
        - config-changed

    - include: upgrade-charm.yml
      tags:
        - upgrade-charm

    - include: docker-cluster.yml
      tags:
        - docker-cluster-relation-changed

    - include: register.yml
      tags:
        - register-relation-changed

    - include: etcd.yml
      tags:
        - etcd-relation-changed
