---
- hosts: all
  handlers:
    - name: open management port
      command: open-port 5001
    - name: join cluster
      docker:
        command="{{join_command}}"
        image=swarm
        state=reloaded
        restart_policy=always
        detach=true
        name="swarm-node"
    - name: manage cluster
      docker:
        command="{{manage_command}}"
        image=swarm
        state=reloaded
        restart_policy=always
        detach=true
        ports=5001:2375
        name="swarm-manage"
  tasks:
    - include: config-changed.yml
      tags:
        - config-changed

    - include: upgrade-charm.yml
      tags:
        - upgrade-charm

    - include: docker-cluster.yml
      tags:
        - docker-cluster-relation-changed

    - include: register.yml
      tags:
        - register-relation-changed

    - include: etcd.yml
      tags:
        - etcd-relation-changed
