---
- name: set state uri
  ini_file: "dest={{docker_facts}}
             section=command
             option=join
             value='{{state_server_uri}}'
             backup=yes"
  notify:
    - join cluster

- name: set commands
  set_fact:
    join_command: "join --addr={{unit_private_address}}:2375 {{state_server_uri}}"
    manage_command: "manage {{state_server_uri}}"

- name: set join command
  ini_file: "dest={{docker_facts}}
             section=command
             option=join
             value='{{join_command}}'
             backup=yes"
  notify:
    - join cluster

- name: set manage command
  ini_file: "dest={{docker_facts}}
             section=command
             option=manage
             value='{{manage_command}}'
             backup=yes"
  notify:
    - manage cluster
    - open management port

- name: set reload
  ini_file: "dest={{docker_facts}}
             section=state
             option=reload
             value=true
             backup=yes"